Set-Content src\main\resources\application.properties @"
spring.application.name=gestion-absences

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.yactikaowvlczvwipqzn
spring.datasource.password=ouiamedatabase19
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.security.user.name=admin
spring.security.user.password=admin

server.port=8081
"@
